<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('form', 'pageTitle');
$this->headTitle($this->escape($this->pageTitle));
?>

<div class="viewMain">
    <h1><?php  ?></h1>
    <div>
      <form  class='genericform' id='configForm' method='POST' action=''>
      <h3> Comment Module Configuration </h3>
      <p>Currently sorting comments by <b><?php if( MidasLoader::loadModel("Setting")->getValueByName("commentOrder","comments") ==0) { echo "OLDEST";} else { echo "NEWEST";};?></b> first.</p>
      <label for"'commentOrder'>Order comments by</label>
      <select name='commentOrder'>
        <option value="<?php echo OLDEST_FIRST ?>">Oldest First</option>
        <option value="<?php echo NEWEST_FIRST ?>">Newest First</option>
      </form>
    </div>
    <div>
      <input type='submit' value='Save Configuration'/>
    </div>
</div>
